version: 2.1
orbs:
  newman: postman/newman@1.0.0
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: /Users/cidivision/FaceRecoTest/FaceRecoTest.postman_collection.json
          environment: /Users/cidivision/FaceRecoTest/FaceReco.postman_environment.json
