version: 2.1
orbs:
  newman: postman/newman@1.0.0
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./FaceRecoTest.postman_collection.json
          environment: ./FaceReco.postman_environment.json
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout1
      - newman/newman-run:
          collection: ./FaceRecoTest.postman_collection.json
          environment: ./FaceReco.postman_environment.json
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout2
      - newman/newman-run:
          collection: ./FaceRecoTest.postman_collection.json
          environment: ./FaceReco.postman_environment.json
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout3
      - newman/newman-run:
          collection: ./FaceRecoTest.postman_collection.json
          environment: ./FaceReco.postman_environment.json
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout4
      - newman/newman-run:
          collection: ./FaceRecoTest.postman_collection.json
          environment: ./FaceReco.postman_environment.json
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout5
      - newman/newman-run:
          collection: ./FaceRecoTest.postman_collection.json
          environment: ./FaceReco.postman_environment.json
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout6
      - newman/newman-run:
          collection: ./FaceRecoTest.postman_collection.json
          environment: ./FaceReco.postman_environment.json
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout7
      - newman/newman-run:
          collection: ./FaceRecoTest.postman_collection.json
          environment: ./FaceReco.postman_environment.json
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout8
      - newman/newman-run:
          collection: ./FaceRecoTest.postman_collection.json
          environment: ./FaceReco.postman_environment.json
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout9
      - newman/newman-run:
          collection: ./FaceRecoTest.postman_collection.json
          environment: ./FaceReco.postman_environment.json          
#/Users/cidivision/FaceRecoTest