version: 2.1
orbs:
  newman: postman/newman@1.0.0
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./FaceRecoTest.postman_collection.json
          environment: ./FaceReco.postman_environment.json
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./FaceRecoTest.postman_collection.json
          environment: ./FaceReco.postman_environment.json
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./FaceRecoTest.postman_collection.json
          environment: ./FaceReco.postman_environment.json
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./FaceRecoTest.postman_collection.json
          environment: ./FaceReco.postman_environment.json
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./FaceRecoTest.postman_collection.json
          environment: ./FaceReco.postman_environment.json
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./FaceRecoTest.postman_collection.json
          environment: ./FaceReco.postman_environment.json
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./FaceRecoTest.postman_collection.json
          environment: ./FaceReco.postman_environment.json
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./FaceRecoTest.postman_collection.json
          environment: ./FaceReco.postman_environment.json
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./FaceRecoTest.postman_collection.json
          environment: ./FaceReco.postman_environment.json
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./FaceRecoTest.postman_collection.json
          environment: ./FaceReco.postman_environment.json          
#/Users/cidivision/FaceRecoTest